global using Microsoft.AspNetCore.Components.Authorization;
global using System.ComponentModel.DataAnnotations;
global using System.Net.Http.Headers;
global using System.Security.Claims;
global using System.Text;
global using System.Text.Json;
global using Blazored.LocalStorage;
global using VOD.Authentication.Models;
global using VOD.Authentication.DTOs;