global using Microsoft.AspNetCore.Components.Authorization;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Text;
global using System.Text.Json;
global using System.Security.Claims;
global using Blazored.LocalStorage;
global using VOD.Application.Common.DTOs;
global using VOD.Application.Common.Extensions;
global using VOD.Application.Common.Services;
global using VOD.Authentication.JWT;
global using VOD.Authentication.DTOs;
global using VOD.Authentication.Classes;
global using VOD.Authentication.Models;
global using VOD.Authentication.HttpClients;
global using VOD.Authentication.Extensions;
global using VOD.Admin.UI.Authentication;
global using VOD.Application.HttpClients;

