global using System.ComponentModel.DataAnnotations;
global using System.Net.Http.Json;
global using System.Text;
global using System.Text.Json;
global using Blazored.LocalStorage;
global using VOD.Application.HttpClients;
global using VOD.Application.Common.DTOs;
global using VOD.Authentication.JWT;
global using VOD.Authentication.Classes;
